### ISSUE TITLE
Annonymity, maybe a core bug?

### ISSUE THREAD

**Issue by CodersBrothers** [blockchain/Sharedcoin#3]
There are some articles that talk about no-annonymity of Sharedcoin. See this http://www.coindesk.com/blockchains-sharedcoin-users-can-identified-says-security-expert/

Or this: http://www.coinjoinsudoku.com/

Something about this?

**Comment by btharper** [comment]
The tool was to be released mid-2014 at https://github.com/kristovatlas/coinjoin-sudoku there is currently, around 6 months after the proposed release date, nothing there. I'm not sure if this was delayed without announcement, or just went quiet. I think the attack vector may be valid. Without analysis across multiple rounds I think it's difficult to asses the overall effectiveness of the attack. The worst case scenario, based on my understanding, is that because of the static fee system and limited number of rounds, if the initial inputs could be linked together, including all intermediate addresses the final payment and inputs could be linked, completely breaking anonymity.

Fixing many of the issues contributing to this would be simple to address in protocol, and would work even better in certain cases where final payment can be divided between transactions. Increasing latency (waiting for a while between transactions), adding inputs across different rounds, and paying out across different outputs (if permitted by receiver; this might not help much because the total received by that address doesn't change).

**Comment by CodersBrothers** [comment]
Thats true, seems that this repo never was published with code... or NSA bought this... xD, maybe only its a troll.

I think that the master keys can be that SharedCoins have a little cpanel with some options like this:
End addresses (All as you want)
Time to send coins
Variable minner tax in each

When you make a payment this payment go to a SharedCoin new address and for other random adresses (example 100) SharedCoins send pieces in random interval minutes until the end of cpanel putted time. This schema needs a pool of some 1000's adresses with little pieces. This can get some huge minner taxes, for example for 100 addresses can be 3$ only for minners... maybe each user can set how many payments want... :P

DarkWallet do a interesting way of coinjoin, without middlemen with comissions.
Bitmixer.io do a cool service too.

**Comment by zootreeves** [comment]
Sharedcoin is no longer vulnerable to this particular type of analysis. There is still work to be done in order to improve other potential weaknesses, increasing latency is one option however the service needs to be convenient in order to attract a larger anonymity set. Network fees have been lowered recently for this reason.

Please remember, Shared Coin does not guarantee anonymity - its stated goal is to make transactions more difficult to analyse and to provide plausible deniability.
